spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
      name: discovery

server:
  port: 8761
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/